### PR TITLE
[W.I.P] Revamp shine syncing (take 2)

### PR DESCRIPTION
**Pull request by EmeraldLoc**
Needs testing. Redid it with the latest changes, much happier with the way it turned out this time. Also, as for the omm api, the shine is using behParams, so it shouldnt be a problem anymore, i think....

### CODE REVIEW

**Comment by EmilyEmmi** [comment]
Hey, was working on fixing some stuff - did you intentionally remove the ability to lose the shine from damage sources other than players? Seems like an odd change.

**Comment by EmeraldLoc** [comment]
I did not take enemies into consideration when removing that code. (Other than enemies lava is the only source of such damage, everything else triggers hook on death) From testing that also is called on pvp attack, which was why it was removed. I’ll do more testing when I get to my computer

Edit:

I'll get to testing this tommorow, I have a couple ideas. If you find one use that though (obv)

**Comment by EmeraldLoc** [comment]
Alright that should be good now.

**Comment by EmilyEmmi** [comment]
Huh, I was just using m.hurtCounter > 0 before. What does (m.marioObj.collidedObjInteractTypes & INTERACT_PLAYER == 0) do?

**Comment by EmeraldLoc** [comment]
From the testing I had done, m.hurtCounter also calls for a player attack, but we want to handle that via on pvp attack. That checks that a player isn’t interacting with you when the damage is taken. I may have done some goofy bad testing though.

**Comment by EmeraldLoc** [comment]
After some testing, im dead wrong lol. Idk where that test came from, sorry about that
¯\\_(ツ)_/¯

**Pull request merged**
